source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef', '~> 11.8'
gem 'rake'
gem 'rubocop', '~> 0.18'
gem 'foodcritic', '~> 3.0.0'
gem 'chefspec', '~> 3.2'
gem 'serverspec', '~> 0.14.2'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'pleaserun'
gem 'stove'
